import '../entities/booking_entity.dart';

/// Abstract repository contract for booking persistence.
abstract class BookingRepository {
  /// Saves a new booking record to the data source.
  /// Returns a unique booking ID generated by the backend database.
  Future<String> createBooking(BookingEntity booking);
}
